name: Inference Test

on:
  workflow_dispatch:

jobs:
  test-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker Image
        run: docker pull shrijaya2146/mlops-a3-inference:latest

      - name: Run Inference Container
        run: docker run --rm shrijaya2146/mlops-a3-inference:latest
